# 背包检查周期，单位tick 20tick = 1秒
check-period: 40

# 日志文件路径，不填就是插件目录 /logs, 重启生效
log-path:

# 单个日志文件大小 单位 kb
file-size: 1024
  
# 最大日志文件数量, 超过会删除旧数据
file-num: 10

# 只输出到日志文件，不输出到控制台
console-silent: false

# 当检测到玩家黑名单物品超过阈值时发送给该玩家的信息
# 占位符 %item% 物品键值  %max% 最大阈值 %current% 当前数量
message: ""

# 警告信息
# 占位符 %item% 物品键值  %max% 最大阈值 %current% 当前数量
warningMessage: ""
# 提示信息的发送间隔，单位毫秒
warningCoolDown: 10000

# 黑名单，储存需要监听的物品及数量
# 格式，物品键值: 提醒数量/没收数量
blacklist:

# 储存物品键及对应的序列化物品
key-map:
